(function (translator) {
	translator.translations["el"] = {
		// javascript alerts or messages
		"testneteditionactivated": "ΕΝΕΡΓΗ ΕΚΔΟΣΗ TESTNET",
		"paperlabelbitcoinaddress": "Διεύθυνση Bitcoin:",
		"paperlabelprivatekey": "Προσωπικό Κλειδί:",
		"paperlabelencryptedkey": "Κρυπτογραφημένο Προσωπικό Κλειδί (Απαιτείται κωδικός)",
		"bulkgeneratingaddresses": "Δημιουργία διευθύνσεων... ",
		"brainalertpassphrasetooshort": "Η φράση κωδικός που δώσατε είναι πολύ αδύναμη.\n\n",
		"brainalertpassphrasewarning": "Προσοχή: Είναι σημαντικό να επιλέξετε μια ισχυρή φράση κωδικό που θα σας προφυλάξει από απόπειρες παραβίασής της τύπου brute force και κλοπή των bitcoins σας.",
		"brainalertpassphrasedoesnotmatch": "Η φράση κωδικός και η επιβεβαίωση της δε συμφωνούν.",
		"detailalertnotvalidprivatekey": "Το κείμενο που εισάγατε δεν αντιστοιχεί σε έγκυρο Προσωπικό Κλειδί",
		"detailconfirmsha256": "Το κείμενο που εισάγατε δεν αντιστοιχεί σε έγκυρο Προσωπικό Κλειδί!\n\nΘα θέλατε να χρησιμοποιηθεί το κείμενο ως κωδικός για τη δημιουργία ενός Προσωπικού Κλειδιού που θα δημιουργηθεί από το SHA265 hash της φράσης κωδικού;\n\nΠροσοχή: Είναι σημαντικό να επιλέξετε έναν ισχυρό κωδικό ώστε να είναι δύσκολο να τον μαντέψει κάποιος και να κλέψει τα bitcoins σας.",
		"bip38alertincorrectpassphrase": "Λάθος φράση κωδικός αποκρυπτογράφησης Προσωπικού Κλειδιού.",
		"bip38alertpassphraserequired": "Απαιτείται η φράση κωδικός για το Κλειδί BIP38",
		"vanityinvalidinputcouldnotcombinekeys": "Μη έγκυρη εισαγωγή. Ο συνδυασμός των κλειδιών είναι αδύνατος.",
		"vanityalertinvalidinputpublickeysmatch": "Μη έγκυρη εισαγωγή. Τα Δημόσια Κλειδιά των δύο εγγραφών είναι όμοια. Πρέπει να εισάγετε δύο διαφορετικά Κλειδιά.",
		"vanityalertinvalidinputcannotmultiple": "Μη έγκυρη εισαγωγή. Δεν είναι δυνατός ο πολλαπλασιασμός δύο Δημόσιων Κλειδιών. Επιλέξτε 'Πρόσθεση' για να προσθέσετε δύο Δημόσια Κλειδιά για δημιουργία μίας Διεύθυνσης Bitcoin.",
		"vanityprivatekeyonlyavailable": "Διαθέσιμο μόνο κατά το συνδυασμό δύο Προσωπικών Κλειδιών",
		"vanityalertinvalidinputprivatekeysmatch": "Μη έγκυρη εισαγωγή. Τα Προσωπικά Κλειδιά των δύο εγγραφών είναι όμοια. Πρέπει να εισάγετε δύο διαφορετικά Κλειδιά.",

		// address type select options
		"paperaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "Εγγενές SegWit (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"bulkaddrtype":   { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "Εγγενές SegWit (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"brainaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "Εγγενές SegWit (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"vanityaddrtype": { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "Εγγενές SegWit (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"splitaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "Εγγενές SegWit (bc1q…)", "taproot": "Taproot (bc1p…)" },

		// address type labels
		"paperlabeladdrtype": "Τύπος διεύθυνσης:",
		"bulklabeladdrtype": "Τύπος διεύθυνσης:",
		"brainlabeladdrtype": "Τύπος διεύθυνσης:",
		"vanitylabeladdrtype": "Τύπος διεύθυνσης:",
		"splitlabeladdrtype": "Τύπος διεύθυνσης:",

		// header and menu html
		"tagline": "Δημιουργός Διευθύνσεων Bitcoin, ανοικτού κώδικα Javascript",
		"generatelabelbitcoinaddress": "Δημιουργία Διεύθυνσης Bitcoin...",
		"generatelabelmovemouse": "ΚΟΥΝΗΣΤΕ το ποντίκι τριγύρω για να προσθέσετε επιπλέον τυχαιότητα...",
		"generatelabelkeypress": "Ή πληκτρολογήστε μερικούς τυχαίους χαρακτήρες σε αυτό το πλαίσιο κειμένου",
		"singlewallet": "Απλό Πορτοφόλι",
		"paperwallet": "Χάρτινο Πορτοφόλι",
		"bulkwallet": "Πολλαπλά Πορτοφόλια",
		"brainwallet": "Μνημονικό Πορτοφόλι",
		"vanitywallet": "Πορτοφόλι Vanity",
		"splitwallet": "Διαιρεμένο Πορτοφόλι",
		"detailwallet": "Λεπτομέρειες Πορτοφολιού",

		// footer html
		"footerlabeldonations": "Δωρεές:",
		"footerlabeltranslatedby": "Μετάφραση: <a href='http://BitcoinX.gr/'><b>BitcoinX.gr</b></a> 1BitcoiNxkUPcTFxwMqxhRiPEiQRzYskf6",
		"footerlabelpgp": "PGP",
		"footerlabelversion": "ιστορικό εκδόσεων",
		"footerlabelgithub": "Αποθετήριο GitHub",
		"footerlabelgithubzip": "zip",
		"footerlabelsig": "Υπογραφή Bitcoin του πηγαίου κώδικα",
		"footerlabelcopyright1": "Copyright bitaddr.org.",
		"footerlabelcopyright2": "Τα πνευματικά δικαιώματα της JavaScript περιλαμβάνονται στον κώδικα.",
		"footerlabelnowarranty": "Καμία εγγύηση.",

		// status html
		"statuslabelcryptogood": "&#10004; Καλά!",
		"statuslabelcryptogood1": "Το πρόγραμμα περιήγησής σας μπορεί να δημιουργήσει κρυπτογραφικά τυχαία κλειδιά χρησιμοποιώντας window.crypto.getRandomValues",
		"statusokcryptogood": "OK",
		"statuslabelcryptobad": "&times; Προσοχή!",
		"statuslabelcryptobad1": "Το πρόγραμμα περιήγησής σας ΔΕΝ υποστηρίζει window.crypto.getRandomValues. Θα πρέπει να χρησιμοποιήσετε ένα πιο σύγχρονο πρόγραμμα περιήγησης για να αυξήσετε την ασφάλεια των κλειδιών που δημιουργούνται.",
		"statusokcryptobad": "OK",
		"statuslabelunittestsgood": "&#10004; Καλά!",
		"statuslabelunittestsgood1": "Όλες οι σύγχρονες δοκιμές μονάδας πέρασαν.",
		"statusokunittestsgood": "OK",
		"statuslabelunittestsbad": "&times; Προσοχή!",
		"statuslabelunittestsbad1": "Ορισμένες σύγχρονες δοκιμές μονάδας ΔΕΝ πέρασαν. Θα πρέπει να βρείτε άλλο πρόγραμμα περιήγησης για να χρησιμοποιήσετε με αυτόν τον γεννήτορα.",
		"statusokunittestsbad": "OK",
		"statuslabelprotocolgood": "&#10004; Καλά!",
		"statuslabelprotocolgood1": "Εκτελείτε αυτόν τον γεννήτορα από τον τοπικό σας υπολογιστή. <br />Συμβουλή: Ελέγξτε ότι είστε εκτός σύνδεσης δοκιμάζοντας ",
		"statusokprotocolgood": "OK",
		"statuslabelprotocolbad": "&#9888; Σκεφτείτε το!",
		"statuslabelprotocolbad1": "Φαίνεται ότι εκτελείτε αυτόν τον γεννήτορα διαδικτυακά από έναν ζωντανό ιστότοπο. Για πολύτιμα πορτοφόλια συνιστάται να",
		"statuslabelprotocolbad2": "κατεβάσετε",
		"statuslabelprotocolbad3": "το αρχείο zip από το GitHub και να εκτελέσετε αυτόν τον γεννήτορα εκτός σύνδεσης ως τοπικό αρχείο html.",
		"statusokprotocolbad": "OK",
		"statuslabelkeypool1": "Αυτό είναι ένα αρχείο καταγραφής όλων των Διευθύνσεων Bitcoin και Προσωπικών Κλειδιών που δημιουργήσατε κατά την τρέχουσα συνεδρία. Η επαναφόρτωση της σελίδας θα δημιουργήσει νέα συνεδρία.",
		"statuskeypoolrefresh": "Ανανέωση",
		"statusokkeypool": "OK",

		// single wallet html
		"newaddress": "Δημιουργία μιας νέας Διεύθυνσης",
		"singleprint": "Εκτύπωση",
		"singlelabelbitcoinaddress": "Διεύθυνση Bitcoin (Legacy P2PKH)",
		"singlelabelP2SH": "P2SH-P2WPKH (3…)",
		"singlelabelSegwit": "Εγγενές SegWit P2WPKH (bc1q…)",
		"singlelabelTaproot": "Taproot P2TR (bc1p…)",
		"singlelabelprivatekey": "Ιδιωτικό Κλειδί (WIF συμπιεσμένο)",
		"singletip1": "<b>Ένα πορτοφόλι Bitcoin</b> είναι τόσο απλό όσο ένα ζευγάρι μιας Διεύθυνσης Bitcoin με το αντίστοιχο Προσωπικό Κλειδί Bitcoin. Ένα τέτοιο πορτοφόλι έχει δημιουργηθεί για εσάς στο πρόγραμμα περιήγησης και εμφανίζεται παραπάνω.",
		"singletip2": "<b>Για να προστατέψετε αυτό το πορτοφόλι</b> πρέπει να εκτυπώσετε ή να καταγράψετε με άλλο τρόπο τη Διεύθυνση Bitcoin και το Προσωπικό Κλειδί. Είναι σημαντικό να δημιουργήσετε αντίγραφο ασφαλείας του Προσωπικού Κλειδιού και να το αποθηκεύσετε σε ασφαλές μέρος. Ο ιστότοπος αυτός δεν έχει γνώση του Προσωπικού Κλειδιού σας. Εάν εγκαταλείψετε ή ανανεώσετε τον ιστότοπο ή πατήσετε το κουμπί Δημιουργία Νέας Διεύθυνσης, τότε θα δημιουργηθεί νέο Προσωπικό Κλειδί και το προηγουμένως εμφανιζόμενο δεν θα είναι ανακτήσιμο. Το Προσωπικό Κλειδί Bitcoin σας πρέπει να παραμείνει μυστικό. Όποιος γνωρίζει το Προσωπικό Κλειδί έχει πρόσβαση να ξοδέψει όλα τα bitcoins που σχετίζονται με αυτή τη διεύθυνση.",
		"singletip3": "<b>Προσθέστε κεφάλαια</b> σε αυτό το πορτοφόλι υποδεικνύοντας σε άλλους να στείλουν bitcoins στη Διεύθυνση Bitcoin σας.",
		"singletip4": "<b>Ελέγξτε το υπόλοιπό σας</b> στο blockchain.info ή blockexplorer.com εισάγοντας τη Διεύθυνση Bitcoin σας.",
		"singletip5": "<b>Ξοδέψτε τα bitcoins σας</b> μεταβαίνοντας στο blockchain.info και μεταφέρτε το πλήρες υπόλοιπο του Προσωπικού Κλειδιού σας στο λογαριασμό σας εκεί. Μπορείτε επίσης να ξοδέψετε τα κεφάλαιά σας κατεβάζοντας ένα από τα δημοφιλή p2p πελατολόγια bitcoin και εισάγοντας το Προσωπικό Κλειδί σας. Ο Satoshi συμβούλευσε ότι δεν πρέπει ποτέ κανείς να διαγράφει ένα πορτοφόλι.",
		"singleshare": "ΚΟΙΝΟΠΟΙΗΣΗ",
		"singlesecret": "ΜΥΣΤΙΚΟ",

		// paper wallet html
		"paperlabelhideart": "Απόκρυψη γραφικού;",
		"paperlabeladdressesperpage": "Διευθύνσεις ανά σελίδα:",
		"paperlabeladdressestogenerate": "Πλήθος διευθύνσεων:",
		"papergenerate": "Δημιουργία",
		"paperprint": "Εκτύπωση",
		"paperlabelBIPpassphrase": "Passphrase:",
		"paperlabelencrypt": "Κρυπτογράφηση BIP38;",

		// bulk wallet html
		"bulklabelstartindex": "Ξεκίνημα δείκτη:",
		"bulklabelrowstogenerate": "Πλήθος σειρών:",
		"bulklabelcompressed": "Συμπιεσμένες διευθύνσεις;",
		"bulkgenerate": "Δημιουργία",
		"bulkprint": "Εκτύπωση",
		"bulklabelcsv": "Τιμές που χωρίζονται με κόμμα (CSV):",
		"bulklabelformat": "Δείκτης,Διεύθυνση,Προσωπικό Κλειδί (WIF)",
		"bulklabelq1": "Γιατί να χρησιμοποιήσω Πολλαπλά Πορτοφόλια στην ιστοσελίδα μου;",
		"bulka1": "Ο παραδοσιακός τρόπος για να δέχεστε bitcoins στην ιστοσελίδα σας, απαιτεί την εγκατάσταση και λειτουργία του επίσημου δαίμονα πελάτη bitcoin (\"bitcoind\"). Αρκετά πακέτα φιλοξενίας δεν υποστηρίζουν την εγκατάστασή του. Επιπλέον, η εκτέλεση του πελάτη bitcoin στον web server σας συνεπάγεται και τη φιλοξενία των προσωπικών σας κλειδιών στον ίδιο server, τα οποία μπορεί να υποκλαπούν αν ο server πέσει θύμα επίθεσης. Χρησιμοποιώντας τα Πολλαπλά Πορτοφόλια, ανεβάζετε στον server σας μόνο τις διευθύνσεις Bitcoin κι όχι τα προσωπικά κλειδιά. Με αυτό τον τρόπο δεν χρειάζεται να ανησυχείτε μήπως υποκλαπεί το πορτοφόλι σας.",
		"bulklabelq2": "Πως χρησιμοποιώ τα Πολλαπλά Πορτοφόλια για να δέχομαι bitcoins στην ιστοσελίδα μου;",
		"bulklabela2li1": "Χρησιμοποιήστε την καρτέλα Πολλαπλά Πορτοφόλια για να δημιουργήσετε έναν μεγάλο αριθμό διευθύνσεων Bitcoin (10.000+). Αντιγράψτε κι επικολλήστε τη λίστα των χωρισμένων με κόμμα τιμών (CSV) που δημιουργήθηκαν, σε ένα ασφαλές αρχείο στον υπολογιστή σας. Αντιγράψτε το αρχείο που δημιουργήσατε σε μια ασφαλή τοποθεσία.",
		"bulklabela2li2": "Εισάγετε τις διευθύνσεις Bitcoin σε έναν πίνακα βάσης δεδομένων στον web server σας. (Μην αντιγράψετε τα προσωπικά κλειδιά ή το πορτοφόλι στον web server γιατί διακινδυνεύετε να σας τα κλέψουν. Μόνο τις διευθύνσεις Bitcoin που θα εμφανίζονται στους πελάτες.)",
		"bulklabela2li3": "Παρέχετε στο καλάθι αγορών σας μια επιλογή για πληρωμή σε Bitcoin. Όταν ο πελάτης επιλέγει να πληρώσει με Bitcoin, θα εμφανίσετε σε αυτόν μια από τις διευθύνσεις από τη βάση δεδομένων, ως την «προσωπική του διεύθυνση πληρωμής» την οποία θα αποθηκεύσετε μαζί με την εντολή αγοράς.",
		"bulklabela2li4": "Τώρα χρειάζεται να ειδοποιηθείτε μόλις γίνει η πληρωμή. Ψάξτε στο Google για «bitcoin payment notification» κι εγγραφείτε σε τουλάχιστο μία υπηρεσία ειδοποίησης πληρωμής. Υπάρχουν διάφορες υπηρεσίες που θα σας ειδοποιήσουν με Web υπηρεσίες, API, SMS, Email, κλπ. Όταν λάβετε την ειδοποίηση, η οποία μπορεί να αυτοματοποιηθεί προγραμματιστικά, εκτελείτε την εντολή του πελάτη. Για να ελέγξετε χειροκίνητα την πληρωμή μπορείτε να χρησιμοποιήσετε τον Block Explorer. Αντικαταστήστε το THEADDRESSGOESHERE με τη Bitcoin διεύθυνσή σας. Η επιβεβαίωση της πληρωμής ενδέχεται να διαρκέσει από δέκα λεπτά έως μία ώρα.<br />http://www.blockexplorer.com/address/THEADDRESSGOESHERE<br /><br />Μπορείτε να δείτε τις συναλλαγές που δεν έχουν επιβεβαιωθεί στο: http://blockchain.info/ <br />Θα πρέπει να δείτε τη συναλλαγή εκεί εντός 30 δευτερολέπτων.",
		"bulklabela2li5": "Τα Bitcoins θα συσσωρεύονται με ασφάλεια στην αλυσίδα των μπλοκ. Χρησιμοποιήστε το αρχικό πορτοφόλι που δημιουργήσατε στο βήμα 1 για να τα ξοδέψετε.",

		// brain wallet html
		"brainlabelenterpassphrase": "Εισάγετε κωδικό: ",
		"brainlabelshow": "Εμφάνιση;",
		"brainprint": "Εκτύπωση",
		"brainlabelconfirm": "Επιβεβαιώστε τον κωδικό: ",
		"brainview": "Δημιουργία",
		"brainalgorithm": "Αλγόριθμος: SHA256(κωδικός)",
		"brainlabelbitcoinaddress": "Διεύθυνση Bitcoin:",
		"brainlabelprivatekey": "Προσωπικό Κλειδί (Μορφή εισαγωγής σε πορτοφόλι):",

		// vanity wallet html
		"vanitylabelstep1": "Βήμα 1 - Δημιουργήστε το «Ζεύγος κλειδιών του Βήματος 1»",
		"vanitynewkeypair": "Δημιουργία",
		"vanitylabelstep1publickey": "Βήμα 1 Δημόσιο Κλειδί:",
		"vanitylabelstep1pubnotes": "Αντιγράψτε κι επικολλήστε το παραπάνω στο πεδίο Your-Part-Public-Key στην ιστοσελίδα του Vanity Pool.",
		"vanitylabelstep1privatekey": "Step 1 Προσωπικό Κλειδί:",
		"vanitylabelstep1privnotes": "Αντιγράψτε κι επικολλήστε το παραπάνω Προσωπικό Κλειδί σε ένα αρχείο κειμένου. Ιδανικά, αποθηκεύστε το σε έναν κρυπτογραφημένο δίσκο. Θα το χρειαστείτε για να ανακτήσετε το Bitcoin Προσωπικό Κλειδί όταν βρεθεί το πρόθεμά σας από το Vanity Pool.",
		"vanitylabelstep2calculateyourvanitywallet": "Βήμα 2 - Υπολογίστε το Vanity Πορτοφόλι σας.",
		"vanitylabelenteryourpart": "Εισάγετε το Προσωπικό Κλειδί που δημιουργήσατε στο Βήμα 1 κι αποθηκεύσατε:",
		"vanitylabelenteryourpoolpart": "Εισάγετε το Προσωπικό Κλειδί από το Vanity Pool:",
		"vanitylabelnote1": "[ΣΗΜΕΙΩΣΗ: Το πεδίο αυτό μπορεί να δεχθεί είτε ένα Δημόσιο είτε ένα Προσωπικό Κλειδί.]",
		"vanitylabelnote2": "[ΣΗΜΕΙΩΣΗ: Το πεδίο αυτό μπορεί να δεχθεί είτε ένα Δημόσιο είτε ένα Προσωπικό Κλειδί.]",
		"vanitylabelradioadd": "Πρόσθεσε",
		"vanitylabelradiomultiply": "Πολλαπλασίασε",
		"vanitycalc": "Υπολογισμός του Πορτοφολιού Vanity",
		"vanitylabelbitcoinaddress": "Vanity Διεύθυνση Bitcoin:",
		"vanitylabelnotesbitcoinaddress": "Παραπάνω είναι η διεύθυνσή σας που θα πρέπει να περιλαμβάνει το επιθυμητό πρόθεμα.",
		"vanitylabelpublickeyhex": "Vanity Δημόσιο Κλειδί (HEX):",
		"vanitylabelnotespublickeyhex": "Παραπάνω είναι το Δημόσιο Κλειδί σε δεκαεξαδική μορφή. ",
		"vanitylabelprivatekey": "Vanity Προσωπικό Κλειδί (WIF):",
		"vanitylabelnotesprivatekey": "Παραπάνω είναι το Προσωπικό Κλειδί που θα φορτώσετε στο Πορτοφόλι σας. ",

		// split wallet html
		"splitlabelthreshold": "Ελάχιστο όριο μετοχών που απαιτείται για συνδυασμό",
		"splitlabelshares": "Αριθμός μετοχών",
		"splitview": "Δημιουργία",
		"combinelabelentershares": "Εισάγετε τις διαθέσιμες μετοχές (διαχωρισμένες με κενό)",
		"combineview": "Συνδυασμός Μετοχών",
		"combinelabelprivatekey": "Συνδυασμένο Προσωπικό Κλειδί",

		// detail wallet html
		"detaillabelenterprivatekey": "Εισάγετε το Προσωπικό Κλειδί",
		"detailkeyformats": "Key Formats: WIF, WIFC, HEX, B64, B6, MINI, BIP38",
		"detailview": "Προβολή λεπτομερειών",
		"detailprint": "Εκτύπωση",
		"detaillabelnote1": "Το Bitcoin Προσωπικό Κλειδί είναι ένας μοναδικός και μυστικός αριθμός που μόνο εσείς πρέπει να γνωρίζετε, ο οποίος μπορεί να κωδικοποιηθεί σε πολλές διαφορετικές μορφές. Εμφανίζουμε παρακάτω τη διεύθυνση Bitcoin και το Δημόσιο Κλειδί, μαζί με το Προσωπικό Κλειδί, στις πιο δημοφιλείς μορφές  (WIF, WIFC, HEX, B64).",
		"detaillabelnote2": "Το Bitcoin v0.6+ αποθηκεύει τα Προσωπικά Κλειδιά σε συμπιεσμένη μορφή. Το πρόγραμμα υποστηρίζει επίσης εισαγωγή κι εξαγωγή των Προσωπικών Κλειδιών με τις εντολές importprivkey/dumpprivkey. Η μορφή του εξαγόμενου Προσωπικού Κλειδιού προσδιορίζεται από το αν η διεύθυνση δημιουργήθηκε σε ένα παλιό ή νέο πορτοφόλι.",
		"detaillabelbitcoinaddress": "Διεύθυνση Bitcoin (Legacy P2PKH)",
		"detaillabelbitcoinaddresscomp": "Συμπιεσμένη Διεύθυνση Bitcoin (Legacy P2PKH)",
		"detaillabelP2SH": "Διεύθυνση P2SH-P2WPKH (3…)",
		"detaillabelSegwit": "Εγγενές SegWit P2WPKH (bc1q…)",
		"detaillabelTaproot": "Taproot P2TR (bc1p…)",
		"detaillabelpublickey": "Δημόσιο Κλειδί (130 χαρακτήρες [0-9A-F]):",
		"detaillabelpublickeycomp": "Δημόσιο Κλειδί (Συμπιεσμένο, 66 χαρακτήρες [0-9A-F]):",
		"detaillabelprivwif": "Προσωπικό Κλειδί WIF (51 χαρακτήρες base58, ξεκινάει με",
		"detaillabelprivwifcomp": "Προσωπικό Κλειδί WIF (Συμπιεσμένο, 52 χαρακτήρες base58, ξεκινάει με",
		"detailcompwifprefix": "'K' ή 'L'",
		"detaillabelprivhex": "Προσωπικό Κλειδί Δεκαεξαδική Μορφή (64 χαρακτήρες [0-9A-F]):",
		"detaillabelprivb64": "Προσωπικό Κλειδί Base64 (44 χαρακτήρες):",
		"detaillabelprivmini": "Προσωπικό Κλειδί Μορφή Mini (22, 26 ή 30 χαρακτήρες, ξεκινάει με 'S'):",
		"detaillabelpassphrase": "BIP38 Κωδικός",
		"detailbip38decryptbutton": "Αποκωδικοποίηση BIP38",
		"detailbip38encryptbutton": "Κωδικοποίηση BIP38",
		"detaillabelq1": "Πώς δημιουργώ ένα πορτοφόλι χρησιμοποιώντας ζάρια; Τι είναι το B6;",
		"detaila1": "Ένα σημαντικό μέρος της δημιουργίας ενός πορτοφολιού Bitcoin είναι η διασφάλιση ότι οι τυχαίοι αριθμοί που χρησιμοποιούνται για τη δημιουργία του πορτοφολιού είναι πραγματικά τυχαίοι. Η φυσική τυχαιότητα είναι καλύτερη από την ψευδοτυχαιότητα που παράγει ο υπολογιστής. Ο πιο εύκολος τρόπος για να δημιουργήσετε φυσική τυχαιότητα είναι με ζάρια. Για να δημιουργήσετε ένα Προσωπικό Κλειδί Bitcoin χρειάζεστε μόνο ένα εξάπλευρο ζάρι το οποίο θα ρίξετε 99 φορές. Σταματώντας κάθε φορά για να καταγράψετε την τιμή. Κατά την καταγραφή των τιμών ακολουθήστε αυτούς τους κανόνες: 1=1, 2=2, 3=3, 4=4, 5=5, 6=0. Κάνοντας αυτό καταγράφετε τον μεγάλο τυχαίο αριθμό, το Προσωπικό Κλειδί σας, σε μορφή B6 ή βάση 6. Μπορείτε στη συνέχεια να εισαγάγετε το Προσωπικό Κλειδί βάσης 6 των 99 χαρακτήρων στο πεδίο κειμένου παραπάνω και να κάνετε κλικ στο Προβολή Λεπτομερειών. Θα δείτε τότε τη Διεύθυνση Bitcoin που σχετίζεται με το Προσωπικό Κλειδί σας. Θα πρέπει επίσης να σημειώσετε το Προσωπικό Κλειδί σας σε μορφή WIF καθώς χρησιμοποιείται ευρύτερα.",
		"bulklabelencrypt": "Κρυπτογράφηση BIP38;",
		"detaillabelencrypt": "Κρυπτογράφηση BIP38;",
		"bulklabelBIPpassphrase": "Passphrase:",
		"brainlabelcompressed": "Συμπιεσμένη διεύθυνση;",
		"detailwifprefix": "'5'",
		"detaillabelprivb6": "Ιδιωτικό κλειδί μορφή Base6 (99 χαρακτήρες [0-5]):"
	};
})(ninja.translator);
