(function (translator) {
	translator.translations["es"] = {
		// javascript alerts or messages
		"testneteditionactivated": "Testnet se activa",
		"paperlabelbitcoinaddress": "Dirección Bitcoin:",
		"paperlabelprivatekey": "Clave privada:",
		"paperlabelencryptedkey": "Clave Privada Cifrada (contraseña requerida)",
		"bulkgeneratingaddresses": "Generación de direcciones... ",
		"brainalertpassphrasetooshort": "La contraseña introducida es demasiado corta.\n\n",
		"brainalertpassphrasewarning": "Aviso: Es importante escoger una contraseña fuerte para evitar ataques de fuerza bruta a fin de adivinarla y robar tus bitcoins.",
		"brainalertpassphrasedoesnotmatch": "Las contraseñas no coinciden.",
		"detailalertnotvalidprivatekey": "El texto que has introducido no es una clave privada válida",
		"detailconfirmsha256": "El texto que has introducido no es una clave privada válida\n\n¿Quieres usar ese texto como si fuera una contraseña y generar una clave privada usando un hash SHA256 de tal contraseña?\n\nAviso: Es importante escoger una contraseña fuerte para evitar ataques de fuerza bruta a fin de adivinarla y robar tus bitcoins.",
		"bip38alertincorrectpassphrase": "Contraseña incorrecta para esta clave privada cifrada.",
		"bip38alertpassphraserequired": "Se requiere contraseña para la clave BIP38",
		"vanityinvalidinputcouldnotcombinekeys": "Entrada no válida. No se puede combinar llaves.",
		"vanityalertinvalidinputpublickeysmatch": "Entrada no válida. La clave pública de ambos coincidan entradas. Debe introducir dos claves diferentes.",
		"vanityalertinvalidinputcannotmultiple": "Entrada no válida. No se puede multiplicar dos claves públicas. Seleccione 'Añadir' para agregar dos claves públicas para obtener una dirección bitcoin.",
		"vanityprivatekeyonlyavailable": "Sólo está disponible cuando se combinan dos claves privadas",
		"vanityalertinvalidinputprivatekeysmatch": "Entrada no válida. La clave privada de ambos coincidan entradas. Debe introducir dos claves diferentes.",

		// address type select options
		"paperaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"bulkaddrtype":   { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"brainaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"vanityaddrtype": { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"splitaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },

		// address type labels
		"paperlabeladdrtype": "Tipo de dirección:",
		"bulklabeladdrtype": "Tipo de dirección:",
		"brainlabeladdrtype": "Tipo de dirección:",
		"vanitylabeladdrtype": "Tipo de dirección:",
		"splitlabeladdrtype": "Tipo de dirección:",

		// header and menu html
		"tagline": "Generador de carteras Bitcoin de código abierto en lado de cliente con Javascript",
		"generatelabelbitcoinaddress": "Generando dirección Bitcoin...",
		"generatelabelmovemouse": "Mueve un poco el ratón para crear entropía...",
		"generatelabelkeypress": "O escribe algunos caracteres aleatorios en este campo de texto",
		"singlewallet": "Una sola cartera",
		"paperwallet": "Cartera en papel",
		"bulkwallet": "Direcciones en masa",
		"brainwallet": "Cartera mental",
		"vanitywallet": "Cartera personalizada",
		"splitwallet": "Billetera Dividida",
		"detailwallet": "Detalles de la cartera",

		// footer html
		"footerlabeldonations": "Donaciones:",
		"footerlabeltranslatedby": "Traducción: <b>12345</b>Vypv2QSmuRXcciT5oEB27mPbWGeva",
		"footerlabelpgp": "PGP",
		"footerlabelversion": "Histórico de versiones",
		"footerlabelgithub": "Repositorio GitHub",
		"footerlabelgithubzip": "zip",
		"footerlabelsig": "sig",
		"footerlabelcopyright1": "Copyright bitaddress.org.",
		"footerlabelcopyright2": "Copyright del código JavaScript: en el fuente.",
		"footerlabelnowarranty": "Sin garantía.",

		// status html
		"statuslabelcryptogood": "&#10004; ¡Bien!",
		"statuslabelcryptogood1": "Tu navegador puede generar claves criptográficamente aleatorias usando window.crypto.getRandomValues",
		"statusokcryptogood": "OK",
		"statuslabelcryptobad": "&times; ¡Atención!",
		"statuslabelcryptobad1": "Tu navegador NO soporta window.crypto.getRandomValues. Deberías usar un navegador más moderno para aumentar la seguridad de las claves generadas.",
		"statusokcryptobad": "OK",
		"statuslabelunittestsgood": "&#10004; ¡Bien!",
		"statuslabelunittestsgood1": "Todos los tests unitarios síncronos pasaron.",
		"statusokunittestsgood": "OK",
		"statuslabelunittestsbad": "&times; ¡Atención!",
		"statuslabelunittestsbad1": "Algunos tests unitarios síncronos NO pasaron. Deberías usar otro navegador para este generador.",
		"statusokunittestsbad": "OK",
		"statuslabelprotocolgood": "&#10004; ¡Bien!",
		"statuslabelprotocolgood1": "Estás ejecutando este generador desde tu ordenador local. <br />Consejo: Verifica que estás desconectado intentando ",
		"statusokprotocolgood": "OK",
		"statuslabelprotocolbad": "&#9888; ¡Piénsalo dos veces!",
		"statuslabelprotocolbad1": "Parece que estás ejecutando este generador en línea desde un sitio web. Para carteras valiosas se recomienda",
		"statuslabelprotocolbad2": "descargar",
		"statuslabelprotocolbad3": "el archivo zip de GitHub y ejecutar este generador sin conexión como archivo HTML local.",
		"statusokprotocolbad": "OK",
		"statuslabelkeypool1": "Este es un registro de todas las Direcciones Bitcoin y Claves Privadas que generaste durante tu sesión actual. Recargar la página creará una nueva sesión.",
		"statuskeypoolrefresh": "Actualizar",
		"statusokkeypool": "OK",

		// single wallet html
		"newaddress": "Generar dirección",
		"singleprint": "Imprimir",
		"singlelabelbitcoinaddress": "Dirección Bitcoin (Legacy P2PKH)",
		"singlelabelP2SH": "P2SH-P2WPKH (3…)",
		"singlelabelSegwit": "SegWit Nativo P2WPKH (bc1q…)",
		"singlelabelTaproot": "Taproot P2TR (bc1p…)",
		"singlelabelprivatekey": "Clave Privada (WIF comprimida)",
		"singletip1": "<b>Una cartera Bitcoin</b> es simplemente un par formado por una dirección Bitcoin y su clave privada correspondiente. Esta cartera ha sido generada en tu navegador y se muestra arriba.",
		"singletip2": "<b>Para proteger esta cartera</b> debes imprimir o anotar la dirección Bitcoin y la clave privada. Es importante hacer una copia de seguridad de la clave privada y guardarla en un lugar seguro. Este sitio no tiene conocimiento de tu clave privada. Si estás familiarizado con PGP, puedes descargar esta página HTML completa y verificar que tienes una versión auténtica del autor del sitio comparando el hash SHA256 de este HTML con el hash SHA256 disponible en el documento de historial de versiones firmado, enlazado en el pie de página de este sitio. Si abandonas/actualizas el sitio o pulsas el botón Generar Nueva Dirección, se generará una nueva clave privada y la anteriormente mostrada no será recuperable. Tu clave privada Bitcoin debe mantenerse en secreto. Cualquiera con quien compartas la clave privada tendrá acceso a gastar todos los bitcoins asociados con esa dirección. Si imprimes tu cartera, guárdala en una bolsa sellada para protegerla del agua. Trata una cartera en papel como efectivo.",
		"singletip3": "<b>Añade fondos</b> a esta cartera indicando a otros que envíen bitcoins a tu dirección Bitcoin.",
		"singletip4": "<b>Comprueba tu saldo</b> en blockchain.info o blockexplorer.com introduciendo tu dirección Bitcoin.",
		"singletip5": "<b>Gasta tus bitcoins</b> en blockchain.info transfiriendo el saldo completo de tu clave privada a tu cuenta en ese sitio. También puedes gastar tus fondos descargando uno de los populares clientes p2p de bitcoin e importando tu clave privada al monedero del cliente. Ten en cuenta que cuando importas tu clave a un cliente p2p y gastas fondos, tu clave se agrupará con otras claves privadas en el monedero del cliente. Cuando realices una transacción, el cambio se enviará a otra dirección bitcoin dentro del monedero del cliente. Entonces debes hacer una copia de seguridad del monedero del cliente p2p y mantenerlo seguro. Satoshi aconsejó que nunca se debe borrar un monedero.",
		"singleshare": "COMPARTIR",
		"singlesecret": "SECRETO",

		// paper wallet html
		"paperlabelhideart": "Ocultar diseño",
		"paperlabeladdressesperpage": "Direcciones por página:",
		"paperlabeladdressestogenerate": "Direcciones en total:",
		"papergenerate": "Generar",
		"paperprint": "Imprimir",
		"paperlabelBIPpassphrase": "Contraseña:",
		"paperlabelencrypt": "¿Cifrar con BIP38?",

		// bulk wallet html
		"bulklabelstartindex": "Empezar en:",
		"bulklabelrowstogenerate": "Filas a generar:",
		"bulklabelcompressed": "¿Direcciones comprimidas?",
		"bulkgenerate": "Generar",
		"bulkprint": "Imprimir",
		"bulklabelcsv": "Valores separados por coma:",
		"bulklabelformat": "Índice,Dirección,Clave privada (formato para importar)",
		"bulklabelq1": "¿Por qué debo usar \"Direcciones en masa\" para aceptar Bitcoins en mi web?",
		"bulka1": "La forma tradicional de aceptar bitcoins en tu web requiere tener instalado el cliente oficial de bitcoin (\"bitcoind\"). Sin embargo muchos servicios de hosting no permiten instalar dicho cliente. Además, ejecutar el cliente en tu servidor supone que las claves privadas están también en el servidor y podrían ser comprometidas en caso de intrusión. Al usar este mecanismo, puedes subir al servidor sólo las dirección de bitcoin y no las claves privadas. De esta forma no te tienes que preocupar de que alguien robe la cartera si se cuelan en el servidor.",
		"bulklabelq2": "¿Cómo uso \"Direcciones en masa\" para aceptar bitcoins en mi web?",
		"bulklabela2li1": "Usa el tab \"Direcciones en masa\" para generar por anticipado muchas direcciones (más de 10000). Copia y pega la lista de valores separados por comas (CSV) a un archivo de texto seguro (cifrado) en tu ordenador. Guarda una copia de seguridad en algún lugar seguro.",
		"bulklabela2li2": "Importa las direcciones en la base de datos de tu servidor. No subas la cartera ni las claves públicas, o de lo contrario te lo pueden robar. Sube sólo las direcciones, ya que es lo que se va a mostrar a los clientes.",
		"bulklabela2li3": "Ofrece una alternativa en el carro de la compra de tu web para que los clientes paguen con Bitcoin. Cuando el cliente elija pagar con Bitcoin, les muestras una de las direcciones de la base de datos como su \"dirección de pago\" y guardas esto junto con el pedido.",
		"bulklabela2li4": "Ahora te hace falta recibir una notificación del pago. Busca en google \"notificación de pagos bitcoin\" (o \"bitcoin payment notification\" en inglés) y suscríbete a alguno de los servicios que aparezcan. Hay varios de ellos, que te pueden notificar vía Web services, API, SMS, email, etc. Una vez te llegue la notificación, lo cual puede ser automatizado, entonces ya puedes procesar el pedido. Para comprobar a mano si has recibido un pago, puedes usar Block Explorer: reemplaza DIRECCION a continuación por la dirección que estés comprobando. La transacción puede tardar entre 10 minutos y una hora en ser confirmada. <br />http://www.blockexplorer.com/address/DIRECCION<br /><br />Puedes ver las transacciones sin confirmar en: http://blockchain.info/ <br />Las transacciones sin confirmar suelen aparecer ahí en unos 30 segundos.",
		"bulklabela2li5": "Las bitcoins que recibas se almacenarán de forma segura en la cadena de bloques. Usa la cartera original que generaste en el paso 1 para usarlas.",

		// brain wallet html
		"brainlabelenterpassphrase": "Contraseña:",
		"brainlabelshow": "Mostrar",
		"brainprint": "Imprimir",
		"brainlabelconfirm": "Confirmar contraseña:",
		"brainview": "Ver",
		"brainalgorithm": "Algoritmo: SHA256(contraseña)",
		"brainlabelbitcoinaddress": "Dirección Bitcoin:",
		"brainlabelprivatekey": "Clave privada (formato para importar):",

		// vanity wallet html
		"vanitylabelstep1": "Paso 1 - Genera tu par de claves",
		"vanitynewkeypair": "Generar",
		"vanitylabelstep1publickey": "Clave pública:",
		"vanitylabelstep1pubnotes": "Copia y pega la línea de arriba en el campo \"Your-Part-Public-Key\" de la web de Vanity Pool.",
		"vanitylabelstep1privatekey": "Clave privada:",
		"vanitylabelstep1privnotes": "Copia y pega la clave privada de arriba en un archivo de texto. Es mejor que lo almacenes en un volumen cifrado. Lo necesitarás para recuperar la clave privada una vez Vanity Pool haya encontrado tu prefijo.",
		"vanitylabelstep2calculateyourvanitywallet": "Paso 2 - Calcula tu cartera personalizada",
		"vanitylabelenteryourpart": "Introduce la clave privada generada en el paso 1, y que has guardado:",
		"vanitylabelenteryourpoolpart": "Introduce la clave privada obtenida de la Vanity Pool:",
		"vanitylabelnote1": "[NOTA: esta casilla de entrada puede aceptar una clave pública o clave privada]",
		"vanitylabelnote2": "[NOTA: esta casilla de entrada puede aceptar una clave pública o clave privada]",
		"vanitylabelradioadd": "Añadir",
		"vanitylabelradiomultiply": "Multiplicar",
		"vanitycalc": "Calcular cartera personalizada",
		"vanitylabelbitcoinaddress": "Dirección Bitcoin personalizada:",
		"vanitylabelnotesbitcoinaddress": "Esta es tu nueva dirección, que debería tener el prefijo deseado.",
		"vanitylabelpublickeyhex": "Clave pública personalizada (HEX):",
		"vanitylabelnotespublickeyhex": "Lo anterior es la clave pública en formato hexadecimal.",
		"vanitylabelprivatekey": "Clave privada personalizada (formato para importar):",
		"vanitylabelnotesprivatekey": "Esto es la clave privada para introducir en tu cartera.",

		// split wallet html
		"splitlabelthreshold": "Umbral mínimo de partes necesarias para combinar",
		"splitlabelshares": "Número de partes",
		"splitview": "Generar",
		"combinelabelentershares": "Introduce las partes disponibles (separadas por espacios)",
		"combineview": "Combinar Partes",
		"combinelabelprivatekey": "Clave Privada Combinada",

		// detail wallet html
		"detaillabelenterprivatekey": "Introduce la clave privada",
		"detailkeyformats": "Key Formats: WIF, WIFC, HEX, B64, B6, MINI, BIP38",
		"detailview": "Ver detalles",
		"detailprint": "Imprimir",
		"detaillabelnote1": "Tu clave privada es un número secreto, único, que sólo tú conoces. Se puede expresar en varios formatos. Aquí abajo mostramos la dirección y la clave pública que se corresponden con tu clave privada, así como la clave privada en los formatos más conocidos (para importar, hex, base64 y mini).",
		"detaillabelnote2": "Bitcoin v0.6+ almacena las claves públicas comprimidas. El cliente también soporta importar/exportar claves privadas usando importprivkey/dumpprivkey. El formato de las claves privadas exportadas depende de si la dirección se generó en una cartera antigua o nueva.",
		"detaillabelbitcoinaddress": "Dirección Bitcoin (Legacy P2PKH)",
		"detaillabelbitcoinaddresscomp": "Dirección Bitcoin Comprimida (Legacy P2PKH)",
		"detaillabelP2SH": "Dirección P2SH-P2WPKH (3…)",
		"detaillabelSegwit": "SegWit Nativo P2WPKH (bc1q…)",
		"detaillabelTaproot": "Taproot P2TR (bc1p…)",
		"detaillabelpublickey": "Clave pública (130 caracteres [0-9A-F]):",
		"detaillabelpublickeycomp": "Clave pública (comprimida, 66 caracteres [0-9A-F]):",
		"detaillabelprivwif": "Clave privada para importar (51 caracteres en base58, empieza con un",
		"detaillabelprivwifcomp": "Clave privada para importar (comprimida, 52 caracteres en base58, empieza con",
		"detailcompwifprefix": "'K' o 'L'",
		"detaillabelprivhex": "Clave privada en formato hexadecimal (64 caracteres [0-9A-F]):",
		"detaillabelprivb64": "Clave privada en base64 (44 caracteres):",
		"detaillabelprivmini": "Clave privada en formato mini (22, 26 o 30 caracteres, empieza por 'S'):",
		"detaillabelpassphrase": "Contraseña BIP38",
		"detailbip38decryptbutton": "Descifrar BIP38",
		"detailbip38encryptbutton": "Cifrar BIP38",
		"detaillabelq1": "¿Cómo creo una cartera usando dados? ¿Qué es B6?",
		"detaila1": "Una parte importante de crear una cartera Bitcoin es asegurarse de que los números aleatorios usados para crearla son verdaderamente aleatorios. La aleatoriedad física es mejor que la pseudo-aleatoriedad generada por ordenador. La manera más fácil de generar aleatoriedad física es con dados. Para crear una clave privada Bitcoin sólo necesitas un dado de seis caras que lanzarás 99 veces. Deteniéndote cada vez para registrar el valor del dado. Al registrar los valores sigue estas reglas: 1=1, 2=2, 3=3, 4=4, 5=5, 6=0. Al hacer esto estás registrando el gran número aleatorio, tu clave privada, en formato B6 o base 6. Puedes entonces introducir la clave privada en base 6 de 99 caracteres en el campo de texto de arriba y hacer clic en Ver Detalles. Entonces verás la dirección Bitcoin asociada con tu clave privada. También deberías anotar tu clave privada en formato WIF ya que es más ampliamente utilizado.",
		"bulklabelencrypt": "¿Cifrar con BIP38?",
		"detaillabelencrypt": "¿Cifrar con BIP38?",
		"bulklabelBIPpassphrase": "Contraseña:",
		"brainlabelcompressed": "¿Dirección comprimida?",
		"detailwifprefix": "'5'",
		"detaillabelprivb6": "Clave privada en formato base6 (99 caracteres [0-5]):"
	};
})(ninja.translator);
