(function (translator) {
	translator.translations["fr"] = {
		// alertes et messages javascript
		"testneteditionactivated": "ÉDITION TESTNET ACTIVÉE",
		"paperlabelbitcoinaddress": "Adresse Bitcoin :",
		"paperlabelprivatekey": "Clé Privée :",
		"paperlabelencryptedkey": "Clé Privée Chiffrée (Mot de passe requis)",
		"bulkgeneratingaddresses": "Génération des adresses... ",
		"brainalertpassphrasetooshort": "La phrase de passe que vous avez saisie est trop courte.\n\n",
		"brainalertpassphrasewarning": "Attention : Choisir une phrase de passe solide est essentiel pour vous protéger des attaques par force brute visant à deviner votre phrase de passe et voler vos Bitcoins.",
		"brainalertpassphrasedoesnotmatch": "La phrase de passe ne correspond pas à la confirmation.",
		"detailalertnotvalidprivatekey": "Le texte saisi n'est pas une Clé Privée valide",
		"detailconfirmsha256": "Le texte saisi n'est pas une Clé Privée valide !\n\nVoulez-vous utiliser ce texte comme phrase de passe et créer une Clé Privée via un hash SHA256 de cette phrase ?\n\nAttention : Choisir une phrase de passe solide est essentiel pour vous protéger des attaques par force brute.",
		"detailbip38decryptbutton": "Déchiffrer BIP38",
		"detailbip38encryptbutton": "Chiffrer BIP38",
		"bip38alertincorrectpassphrase": "Phrase de passe incorrecte pour cette clé privée chiffrée.",
		"bip38alertpassphraserequired": "Une phrase de passe est requise pour la clé BIP38",
		"vanityinvalidinputcouldnotcombinekeys": "Entrée invalide. Impossible de combiner les clés.",
		"vanityalertinvalidinputpublickeysmatch": "Entrée invalide. Les Clés Publiques des deux entrées sont identiques. Vous devez saisir deux clés différentes.",
		"vanityalertinvalidinputcannotmultiple": "Entrée invalide. Il est impossible de multiplier deux clés publiques. Sélectionnez « Ajouter » pour additionner deux clés publiques.",
		"vanityprivatekeyonlyavailable": "Disponible uniquement lors de la combinaison de deux clés privées",
		"vanityalertinvalidinputprivatekeysmatch": "Entrée invalide. Les Clés Privées des deux entrées sont identiques. Vous devez saisir deux clés différentes.",

		// options des sélecteurs de type d'adresse
		"paperaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Natif (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"bulkaddrtype":   { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Natif (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"brainaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Natif (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"vanityaddrtype": { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Natif (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"splitaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Natif (bc1q…)", "taproot": "Taproot (bc1p…)" },

		// libellés de type d'adresse
		"paperlabeladdrtype": "Type d'adresse :",
		"bulklabeladdrtype": "Type d'adresse :",
		"brainlabeladdrtype": "Type d'adresse :",
		"vanitylabeladdrtype": "Type d'adresse :",
		"splitlabeladdrtype": "Type d'adresse :",

		// en-tête et menu
		"tagline": "Générateur De Porte-Monnaie Bitcoin Javascript Hors-Ligne",
		"generatelabelbitcoinaddress": "Création de l'adresse Bitcoin...",
		"generatelabelmovemouse": "BOUGEZ votre souris pour ajouter de l'entropie...",
		"generatelabelkeypress": "OU tapez des caractères aléatoires dans le champ ci-dessous",
		"singlewallet": "Porte-Monnaie Simple",
		"paperwallet": "Porte-Monnaie Papier",
		"bulkwallet": "Porte-Monnaie En Vrac",
		"brainwallet": "Porte-Monnaie Cerveau",
		"vanitywallet": "Porte-Monnaie Vanité",
		"splitwallet": "Porte-Monnaie Partagé",
		"detailwallet": "Détails du Porte-Monnaie",

		// porte-monnaie simple
		"newaddress": "Générer Une Nouvelle Adresse",
		"singleprint": "Imprimer",
		"singlelabelbitcoinaddress": "Adresse Bitcoin (Legacy P2PKH)",
		"singlelabelP2SH": "P2SH-P2WPKH (3…)",
		"singlelabelSegwit": "SegWit Natif P2WPKH (bc1q…)",
		"singlelabelTaproot": "Taproot P2TR (bc1p…)",
		"singlelabelprivatekey": "Clé Privée (WIF compressé)",
		"singleshare": "PARTAGER",
		"singlesecret": "SECRET",
		"singletip1": "Un porte-monnaie Bitcoin est simplement une paire constituée d'une adresse Bitcoin et de la clé privée correspondante. Ce porte-monnaie a été généré dans votre navigateur et est affiché ci-dessus.",
		"singletip2": "Pour sécuriser ce porte-monnaie, imprimez-le ou enregistrez l'adresse et la clé privée. Il est important de conserver une copie de sauvegarde de la clé privée dans un endroit sûr. Ce site ne conserve aucune trace de votre clé privée. Si vous quittez ou rafraîchissez la page, ou cliquez sur « Générer Une Nouvelle Adresse », une nouvelle clé privée sera créée et l'ancienne sera définitivement perdue. Votre clé privée Bitcoin doit rester secrète — quiconque la possède peut dépenser vos fonds. Si vous imprimez votre porte-monnaie, conservez-le à l'abri de l'humidité. Traitez un porte-monnaie papier comme des espèces.",
		"singletip3": "Pour alimenter ce porte-monnaie, demandez à vos correspondants d'envoyer des Bitcoins à votre adresse Bitcoin.",
		"singletip4": "Vérifiez votre solde sur blockchain.info ou blockexplorer.com en y renseignant votre adresse Bitcoin.",
		"singletip5": "Pour dépenser vos Bitcoins, rendez-vous sur blockchain.info et effectuez un « sweep » (transfert total) de votre clé privée. Vous pouvez aussi importer la clé dans un client Bitcoin. Notez que lors d'une transaction, la monnaie restante sera renvoyée vers une nouvelle adresse du portefeuille — pensez à effectuer une sauvegarde.",

		// porte-monnaie papier
		"paperlabelhideart": "Masquer l'image ?",
		"paperlabeladdressesperpage": "Adresses par page :",
		"paperlabeladdressestogenerate": "Nombre d'adresses à générer :",
		"papergenerate": "Générer",
		"paperprint": "Imprimer",
		"paperlabelBIPpassphrase": "Phrase de passe :",
		"paperlabelencrypt": "Chiffrement BIP38 ?",

		// porte-monnaie en vrac
		"bulklabelstartindex": "Index de départ :",
		"bulklabelrowstogenerate": "Lignes à générer :",
		"bulklabelcompressed": "Adresses compressées ?",
		"bulkgenerate": "Générer",
		"bulkprint": "Imprimer",
		"bulklabelcsv": "Valeurs Séparées Par Des Virgules (CSV) :",
		"bulklabelformat": "Index,Adresse,Clé Privée (WIF)",
		"bulklabelencrypt": "Chiffrement BIP38 ?",
		"bulklabelBIPpassphrase": "Phrase de passe :",
		"bulklabelq1": "Pourquoi utiliser un Porte-Monnaie En Vrac pour accepter les Bitcoins sur mon site ?",
		"bulka1": "L'approche traditionnelle pour accepter des Bitcoins sur votre site requiert l'installation du daemon Bitcoin officiel (« bitcoind »). De nombreux hébergeurs ne supportent pas ce daemon. De plus, l'exécuter sur votre serveur web signifie que vos clés privées y sont stockées et pourraient être volées en cas de piratage. En utilisant un Porte-Monnaie En Vrac, vous n'uploadez que les adresses Bitcoin sur votre serveur, sans les clés privées. Votre porte-monnaie ne risque donc pas d'être volé même si le serveur est compromis.",
		"bulklabelq2": "Comment utiliser le Porte-Monnaie En Vrac pour accepter les Bitcoins sur mon site ?",
		"bulklabela2li1": "Utilisez l'onglet Porte-Monnaie En Vrac pour pré-générer un grand nombre d'adresses Bitcoin (10 000+). Copiez-collez les données CSV dans un fichier texte sécurisé. Sauvegardez ce fichier en lieu sûr.",
		"bulklabela2li2": "Importez les adresses Bitcoin dans une base de données sur votre serveur web. (N'y mettez pas les clés privées — seulement les adresses visibles par les clients.)",
		"bulklabela2li3": "Proposez le paiement en Bitcoin dans votre panier. Quand un client choisit Bitcoin, affichez-lui une adresse de votre base de données et associez-la à sa commande.",
		"bulklabela2li4": "Abonnez-vous à un service de notification de paiement Bitcoin pour être averti des transactions. Une fois la notification reçue, traitez la commande. Pour vérifier manuellement, utilisez Block Explorer en remplaçant ADRESSE par l'adresse à vérifier.",
		"bulklabela2li5": "Les Bitcoins s'accumulent en toute sécurité sur la blockchain. Utilisez le fichier de porte-monnaie généré à l'étape 1 pour les dépenser.",

		// porte-monnaie cerveau
		"brainlabelenterpassphrase": "Phrase de passe : ",
		"brainlabelshow": "Afficher ?",
		"brainprint": "Imprimer",
		"brainlabelconfirm": "Confirmer la phrase de passe : ",
		"brainlabelcompressed": "Adresse compressée ?",
		"brainview": "Visualiser",
		"brainalgorithm": "Algorithme : SHA256(phrase de passe)",
		"brainlabelbitcoinaddress": "Adresse Bitcoin :",
		"brainlabelprivatekey": "Clé Privée (Format d'importation) :",

		// porte-monnaie vanité
		"vanitylabelstep1": "Étape 1 — Générer votre paire de clés",
		"vanitynewkeypair": "Générer",
		"vanitylabelstep1publickey": "Clé Publique (Étape 1) :",
		"vanitylabelstep1pubnotes": "Copiez-collez cette clé dans le champ « Votre Clé Publique » du site Vanity Pool.",
		"vanitylabelstep1privatekey": "Clé Privée (Étape 1) :",
		"vanitylabelstep1privnotes": "Copiez-collez cette Clé Privée dans un fichier texte. Idéalement, sauvegardez-la sur un support chiffré. Elle sera nécessaire pour récupérer la Clé Privée une fois que Vanity Pool aura trouvé votre préfixe.",
		"vanitylabelstep2calculateyourvanitywallet": "Étape 2 — Calculer votre Porte-Monnaie Vanité",
		"vanitylabelenteryourpart": "Entrez votre Clé Privée (générée à l'étape 1 et préalablement sauvegardée) :",
		"vanitylabelnote1": "[NOTE : ce champ accepte une clé publique ou une clé privée]",
		"vanitylabelenteryourpoolpart": "Entrez la Clé Privée du Pool (issue de Vanity Pool) :",
		"vanitylabelnote2": "[NOTE : ce champ accepte une clé publique ou une clé privée]",
		"vanitylabelradioadd": "Ajouter",
		"vanitylabelradiomultiply": "Multiplier",
		"vanitycalc": "Calculer le Porte-Monnaie Vanité",
		"vanitylabelbitcoinaddress": "Adresse Bitcoin Vanité :",
		"vanitylabelnotesbitcoinaddress": "L'adresse ci-dessus est votre nouvelle adresse qui devrait inclure le préfixe désiré.",
		"vanitylabelpublickeyhex": "Clé Publique Vanité (HEX) :",
		"vanitylabelnotespublickeyhex": "La Clé Publique en format hexadécimal.",
		"vanitylabelprivatekey": "Clé Privée Vanité (WIF) :",
		"vanitylabelnotesprivatekey": "La Clé Privée à importer dans votre porte-monnaie.",

		// porte-monnaie partagé
		"splitlabelthreshold": "Nombre minimum de parts pour reconstituer",
		"splitlabelshares": "Nombre de parts",
		"splitview": "Générer",
		"combinelabelentershares": "Entrez les parts disponibles (séparées par des espaces)",
		"combineview": "Reconstituer",
		"combinelabelprivatekey": "Clé Privée Reconstituée",

		// détails du porte-monnaie
		"detaillabelenterprivatekey": "Entrez la Clé Privée",
		"detailkeyformats": "Formats : WIF, WIFC, HEX, B64, B6, MINI, BIP38",
		"detailview": "Voir les Détails",
		"detailprint": "Imprimer",
		"detaillabelencrypt": "Chiffrer en BIP38 ?",
		"detaillabelpassphrase": "Phrase de passe BIP38",
		"detaillabelnote1": "Votre Clé Privée Bitcoin est un nombre secret connu de vous seul. Elle peut être encodée sous différents formats. Ci-dessous sont affichés l'adresse Bitcoin et la Clé Publique correspondant à votre Clé Privée, ainsi que la Clé Privée dans les formats les plus courants (WIF, WIFC, HEX, B64).",
		"detaillabelnote2": "Bitcoin v0.6+ conserve les clés publiques en format compressé. Le client supporte désormais l'import/export de clés privées via importprivkey/dumpprivkey. Le format de la clé exportée dépend du type de porte-monnaie d'origine.",
		"detaillabelbitcoinaddress": "Adresse Bitcoin (Legacy P2PKH)",
		"detaillabelbitcoinaddresscomp": "Adresse Bitcoin Compressée (Legacy P2PKH)",
		"detaillabelP2SH": "Adresse P2SH-P2WPKH (3…)",
		"detaillabelSegwit": "SegWit Natif P2WPKH (bc1q…)",
		"detaillabelTaproot": "Taproot P2TR (bc1p…)",
		"detaillabelpublickey": "Clé Publique (130 caractères [0-9A-F]) :",
		"detaillabelpublickeycomp": "Clé Publique compressée (66 caractères [0-9A-F]) :",
		"detaillabelprivwif": "Clé Privée WIF\n51 caractères base58, commence par un",
		"detailwifprefix": "« 5 »",
		"detaillabelprivwifcomp": "Clé Privée WIF compressée\n52 caractères base58, commence par un",
		"detailcompwifprefix": "« K » ou « L »",
		"detaillabelprivhex": "Clé Privée Format Hexadécimal (64 caractères [0-9A-F]) :",
		"detaillabelprivb64": "Clé Privée Base64 (44 caractères) :",
		"detaillabelprivmini": "Clé Privée Format Mini (22, 26 ou 30 caractères, commence par « S ») :",
		"detaillabelprivb6": "Clé Privée Format Base6 (99 caractères [0-5]) :",
		"detaillabelq1": "Comment créer un porte-monnaie avec des dés ? Qu'est-ce que B6 ?",
		"detaila1": "Une partie importante de la création d'un porte-monnaie Bitcoin consiste à s'assurer que les nombres aléatoires utilisés sont véritablement aléatoires. L'aléatoire physique est supérieur au pseudo-aléatoire informatique. Le moyen le plus simple est d'utiliser des dés. Pour créer une clé privée Bitcoin, lancez un dé à six faces 99 fois et notez chaque résultat selon la règle : 1=1, 2=2, 3=3, 4=4, 5=5, 6=0. Vous obtenez ainsi votre clé privée en format B6 (base 6). Saisissez ensuite les 99 caractères dans le champ ci-dessus et cliquez sur « Voir les Détails ».",

		// pied de page
		"footerlabeldonations": "Dons :",
		"footerlabeltranslatedby": "Traduction : 1Gy7NYSJNUYqUdXTBow5d7bCUEJkUFDFSq",
		"footerlabelpgp": "PGP",
		"footerlabelversion": "Historique des Versions",
		"footerlabelgithub": "Dépôt GitHub",
		"footerlabelgithubzip": "zip",
		"footerlabelsig": "sig",
		"footerlabelcopyright1": "Copyright bitaddr.org.",
		"footerlabelcopyright2": "Les droits d'auteur JavaScript sont inclus dans le code source.",
		"footerlabelnowarranty": "Aucune garantie.",

		// barre de statut
		"statuslabelcryptogood": "&#10004; Parfait !",
		"statuslabelcryptogood1": "Votre navigateur peut générer des clés cryptographiquement aléatoires via window.crypto.getRandomValues",
		"statusokcryptogood": "OK",
		"statuslabelcryptobad": "&times; Attention !",
		"statuslabelcryptobad1": "Votre navigateur ne supporte PAS window.crypto.getRandomValues. Utilisez un navigateur plus récent pour améliorer la sécurité des clés générées.",
		"statusokcryptobad": "OK",
		"statuslabelunittestsgood": "&#10004; Parfait !",
		"statuslabelunittestsgood1": "Tous les tests unitaires synchrones ont réussi.",
		"statusokunittestsgood": "OK",
		"statuslabelunittestsbad": "&times; Attention !",
		"statuslabelunittestsbad1": "Certains tests unitaires synchrones ont ÉCHOUÉ. Utilisez un autre navigateur pour ce générateur.",
		"statusokunittestsbad": "OK",
		"statuslabelprotocolgood": "&#10004; Parfait !",
		"statuslabelprotocolgood1": "Vous exécutez ce générateur depuis votre ordinateur local. <br />Conseil : Vérifiez que vous êtes bien hors ligne en essayant ",
		"statusokprotocolgood": "OK",
		"statuslabelprotocolbad": "&#9888; Réfléchissez !",
		"statuslabelprotocolbad1": "Vous semblez utiliser ce générateur en ligne depuis un site web. Pour des porte-monnaies de valeur, il est recommandé de",
		"statuslabelprotocolbad2": "télécharger",
		"statuslabelprotocolbad3": "le fichier zip depuis GitHub et d'exécuter ce générateur hors ligne en tant que fichier HTML local.",
		"statusokprotocolbad": "OK",
		"statuslabelkeypool1": "Ceci est un journal de toutes les adresses Bitcoin et clés privées générées durant votre session. Recharger la page créera une nouvelle session.",
		"statuskeypoolrefresh": "Actualiser",
		"statusokkeypool": "OK"
	};
})(ninja.translator);
