(function (translator) {
	translator.translations["pt-br"] = {
		// javascript alerts or messages
		"testneteditionactivated": "EDIÇÃO DA TESTNET ATIVADA",
		"paperlabelbitcoinaddress": "Endereço Bitcoin:",
		"paperlabelprivatekey": "Chave privada:",
		"paperlabelencryptedkey": "Chave privada criptografada (Senha necessária)",
		"bulkgeneratingaddresses": "Gerando endereços... ",
		"brainalertpassphrasetooshort": "A senha introduzida é pequena demais.\n\n",
		"brainalertpassphrasewarning": "Aviso: É importante que você escolha uma senha forte, para evitar ataques de força bruta que tentem adivinhar sua senha e roubar seus bitcoins.",
		"brainalertpassphrasedoesnotmatch": "As senhas digitadas não são iguais.",
		"detailalertnotvalidprivatekey": "O texto que você digitou não é uma chave privada válida",
		"detailconfirmsha256": "O texto que você digitou não é uma chave privada válida\n\nDeseja usar esse texto como se fosse uma senha e gerar uma chave privada usando um hash SHA256 dessa senha?\n\nAviso: É importante escolher uma senha forte para evitar ataques de força bruta que tentem adivinhá-la e roubar seus bitcoins.",
		"bip38alertincorrectpassphrase": "Senha incorreta para essa chave privada criptografada.",
		"bip38alertpassphraserequired": "Senha necessária para a chave BIP38",
		"vanityinvalidinputcouldnotcombinekeys": "Entrada inválida. Não foi possível combinar as chaves.",
		"vanityalertinvalidinputpublickeysmatch": "Entrada inválida. As chaves públicas de ambas as entradas são iguais. Você deve inserir duas chaves diferentes.",
		"vanityalertinvalidinputcannotmultiple": "Entrada inválida. Não é possível multiplicar duas chaves públicas. Clique em 'Somar' e some duas chaves públicas para adquirir um endereço bitcoin.",
		"vanityprivatekeyonlyavailable": "Disponível apenas quando se combinam duas chaves privadas",
		"vanityalertinvalidinputprivatekeysmatch": "Entrada inválida. As chaves privadas de ambas as entradas são iguais. Você deve inserir duas chaves diferentes.",

		// address type select options
		"paperaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"bulkaddrtype":   { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"brainaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"vanityaddrtype": { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },
		"splitaddrtype":  { "legacy": "Legacy P2PKH (1…)", "p2sh": "P2SH-P2WPKH (3…)", "segwit": "SegWit Nativo (bc1q…)", "taproot": "Taproot (bc1p…)" },

		// address type labels
		"paperlabeladdrtype": "Tipo de endereço:",
		"bulklabeladdrtype": "Tipo de endereço:",
		"brainlabeladdrtype": "Tipo de endereço:",
		"vanitylabeladdrtype": "Tipo de endereço:",
		"splitlabeladdrtype": "Tipo de endereço:",

		// header and menu html
		"tagline": "Gerador local de carteiras Bitcoin usando Javascript de código aberto",
		"generatelabelbitcoinaddress": "Gerando endereço Bitcoin...",
		"generatelabelmovemouse": "Movimente um pouco o ponteiro do mouse para criar entropia...",
		"generatelabelkeypress": "OU digite alguns caracteres aleatórios nessa caixa de texto",
		"singlewallet": "Carteira única",
		"paperwallet": "Carteira em papel",
		"bulkwallet": "Múltiplos endereços",
		"brainwallet": "Carteira mental",
		"vanitywallet": "Carteira personalizada",
		"splitwallet": "Carteira Dividida",
		"detailwallet": "Detalhes da carteira",

		// footer html
		"footerlabeldonations": "Doações:",
		"footerlabeltranslatedby": "Tradução: 1LwaSNTZ7xAagYKyE68gT5iqX1DmPnmJmy",
		"footerlabelpgp": "PGP",
		"footerlabelversion": "Histórico de versões",
		"footerlabelgithub": "Repositório GitHub",
		"footerlabelgithubzip": "zip",
		"footerlabelsig": "Assinatura Bitcoin do código-fonte",
		"footerlabelcopyright1": "Copyright bitaddr.org.",
		"footerlabelcopyright2": "Copyright do código JavaScript: no código-fonte.",
		"footerlabelnowarranty": "Sem garantia.",

		// status html
		"statuslabelcryptogood": "&#10004; Ótimo!",
		"statuslabelcryptogood1": "Seu navegador pode gerar chaves criptograficamente aleatórias usando window.crypto.getRandomValues",
		"statusokcryptogood": "OK",
		"statuslabelcryptobad": "&times; Oh não!",
		"statuslabelcryptobad1": "Seu navegador NÃO suporta window.crypto.getRandomValues. Você deve usar um navegador mais moderno para aumentar a segurança das chaves geradas.",
		"statusokcryptobad": "OK",
		"statuslabelunittestsgood": "&#10004; Ótimo!",
		"statuslabelunittestsgood1": "Todos os testes unitários síncronos passaram.",
		"statusokunittestsgood": "OK",
		"statuslabelunittestsbad": "&times; Oh não!",
		"statuslabelunittestsbad1": "Alguns testes unitários síncronos NÃO passaram. Você deve usar outro navegador para este gerador.",
		"statusokunittestsbad": "OK",
		"statuslabelprotocolgood": "&#10004; Ótimo!",
		"statuslabelprotocolgood1": "Você está executando este gerador a partir do seu computador local. <br />Dica: Verifique se você está offline tentando ",
		"statusokprotocolgood": "OK",
		"statuslabelprotocolbad": "&#9888; Pense duas vezes!",
		"statuslabelprotocolbad1": "Parece que você está executando este gerador online a partir de um site ativo. Para carteiras valiosas recomenda-se",
		"statuslabelprotocolbad2": "download",
		"statuslabelprotocolbad3": "o arquivo zip do GitHub e execute este gerador offline como um arquivo html local.",
		"statusokprotocolbad": "OK",
		"statuslabelkeypool1": "Este é um registro de todos os Endereços Bitcoin e Chaves Privadas que você gerou durante a sessão atual. Recarregar a página criará uma nova sessão.",
		"statuskeypoolrefresh": "Atualizar",
		"statusokkeypool": "OK",

		// single wallet html
		"newaddress": "Gerar endereço",
		"singleprint": "Imprimir",
		"singlelabelbitcoinaddress": "Endereço Bitcoin (Legacy P2PKH)",
		"singlelabelP2SH": "P2SH-P2WPKH (3…)",
		"singlelabelSegwit": "SegWit Nativo P2WPKH (bc1q…)",
		"singlelabelTaproot": "Taproot P2TR (bc1p…)",
		"singlelabelprivatekey": "Chave Privada (WIF comprimida)",
		"singletip1": "<b>Uma carteira Bitcoin</b> nada mais é do que um endereço Bitcoin e a sua chave privada Bitcoin correspondente. Essa carteira foi gerada para você em seu navegador web e está sendo exibida acima.",
		"singletip2": "<b>Para proteger essa carteira</b> você deve imprimir ou anotar/salvar o endereço Bitcoin e a sua chave privada correspondente. É importante que você faça uma cópia de segurança da sua chave privada e armazene-a em um local seguro. Esse site não toma conhecimento da sua chave privada. Se você for familiar com criptografia PGP, você pode baixar essa página HTML em um arquivo único e verificar se você tem uma versão autêntica do autor deste site ao fazer a correspondência do hash SHA256 deste HTML com o hash SHA256 disponível na versão assinada do arquivo contido no link no rodapé deste site. Se você sair/atualizar essa página ou apertar o botão Gerar Novo Endereço, então uma nova chave privada será gerada e a chave exibida anteriormente não será recuperável. A sua chave privada Bitcoin deve ser mantida em um segredo. Qualquer pessoa que tiver acesso a ela poderá gastar todos os seus bitcoins associados com aquele endereço. Se você imprimir sua carteira, armazene-a em um saco plástico selado para mantê-la longe da água. Trate sua carteira em papel como se fosse dinheiro.",
		"singletip3": "<b>Adicione fundos</b> para essa carteira ao indicar para outras pessoas enviarem bitcoins para o seu endereço Bitcoin.",
		"singletip4": "<b>Verifique seu saldo</b> visitando os sites blockchain.info ou blockexplorer.com e digitando o seu endereço Bitcoin.",
		"singletip5": "<b>Gaste seus bitcoins</b> visitando o site blockchain.info e esvaziando completamente o seu saldo de sua chave privada para sua conta no site. Você também pode gastar seus fundos ao baixar um cliente bitcoin p2p popular e importar sua chave privada para a carteira do aplicativo. Tenha em mente que quando você importa uma chave única para um cliente bitcoin p2p e gasta seus fundos, sua chave será agrupada com outras chaves privadas no aplicativo de carteira. Quando você realizar uma transação o seu troco será enviado para outro endereço bitcoin dentro do seu aplicativo de carteira. Você deve então fazer backup da sua carteira em seu aplicativo e mantê-la em segurança. Um conselho do Satoshi Nakamoto é de que uma carteira nunca deve ser apagada.",
		"singleshare": "COMPARTILHE",
		"singlesecret": "SECRETA",

		// paper wallet html
		"paperlabelhideart": "Ocultar figura",
		"paperlabeladdressesperpage": "Endereços por página:",
		"paperlabeladdressestogenerate": "Total de endereços:",
		"papergenerate": "Gerar",
		"paperprint": "Imprimir",
		"paperlabelBIPpassphrase": "Senha:",
		"paperlabelencrypt": "Criptografar em BIP38?",

		// bulk wallet html
		"bulklabelstartindex": "Começar em:",
		"bulklabelrowstogenerate": "Linhas a gerar:",
		"bulklabelcompressed": "Endereços comprimidos?",
		"bulkgenerate": "Gerar",
		"bulkprint": "Imprimir",
		"bulklabelcsv": "Valores separados por vírgula:",
		"bulklabelformat": "Índice,Endereço,Chave privada (formato para importar)",
		"bulklabelq1": "Por que devo usar \"Múltiplos endereços\" para aceitar Bitcoins no meu site?",
		"bulka1": "A forma tradicional de aceitar bitcoins no seu site requer ter instalado o cliente oficial de bitcoin (\"bitcoind\"). No entanto muitos serviços de hospedagem não permitem instalar tal cliente. Além disso, executar o cliente no seu servidor significa que as chaves privadas também estão no servidor e poderiam ser comprometidas em caso de intrusão. Ao usar esse mecanismo, você pode enviar ao servidor apenas o endereço de bitcoin e não as chaves privadas. Desta forma, você não precisa se preocupar que alguém roube a carteira se invadirem o servidor.",
		"bulklabelq2": "Como uso \"Múltiplos endereços\" para aceitar bitcoins no meu site?",
		"bulklabela2li1": "Use a aba \"Múltiplos endereços\" para gerar antecipadamente muitos endereços (mais de 10000). Copie e cole a lista de valores separados por vírgulas (CSV) em um arquivo de texto seguro (criptografado) no seu computador. Guarde uma cópia de segurança em algum lugar seguro.",
		"bulklabela2li2": "Importe os endereços no banco de dados do seu servidor. Não envie a carteira nem as chaves privadas, caso contrário elas podem ser roubadas. Envie apenas os endereços, que são o que será mostrado aos clientes.",
		"bulklabela2li3": "Ofereça uma alternativa no carrinho de compras do seu site para que os clientes paguem com Bitcoin. Quando o cliente escolher pagar com Bitcoin, mostre-lhe um dos endereços do banco de dados como seu \"endereço de pagamento\" e guarde isso junto com o pedido.",
		"bulklabela2li4": "Agora você precisa receber uma notificação do pagamento. Pesquise no Google \"bitcoin payment notification\" e inscreva-se em algum dos serviços que aparecerem. Há vários deles, que podem notificá-lo via Web services, API, SMS, email, etc. Uma vez recebida a notificação, o que pode ser automatizado, você pode então processar o pedido. Para verificar manualmente se você recebeu um pagamento, você pode usar o Block Explorer: substitua ENDERECO a seguir pelo endereço que você está verificando. A transação pode demorar entre 10 minutos e uma hora para ser confirmada. <br />http://www.blockexplorer.com/address/ENDERECO<br /><br />Você pode ver as transações não confirmadas em: http://blockchain.info/ <br />As transações não confirmadas geralmente aparecem lá em cerca de 30 segundos.",
		"bulklabela2li5": "Os bitcoins que você receber serão armazenados de forma segura na cadeia de blocos. Use a carteira original que você gerou no passo 1 para utilizá-los.",

		// brain wallet html
		"brainlabelenterpassphrase": "Senha:",
		"brainlabelshow": "Mostrar",
		"brainprint": "Imprimir",
		"brainlabelconfirm": "Confirmar senha:",
		"brainview": "Ver",
		"brainalgorithm": "Algoritmo: SHA256(senha)",
		"brainlabelbitcoinaddress": "Enderçeo Bitcoin:",
		"brainlabelprivatekey": "Chave privada (Wallet Import Format):",

		// vanity wallet html
		"vanitylabelstep1": "Passo 1 - Gere seu par de chaves",
		"vanitynewkeypair": "Gerar",
		"vanitylabelstep1publickey": "Chave pública:",
		"vanitylabelstep1pubnotes": "Copie e cole a linha acima no campo \"Your-Part-Public-Key\" presente no site do Vanity Pool.",
		"vanitylabelstep1privatekey": "Chave privada:",
		"vanitylabelstep1privnotes": "Copie e cole a chave privada acima em um arquivo de texto. Idealmente salve em um disco criptografado. Ela será necessária para recuperar a chave privada assim que a Vanity Pool encontrar o seu prefixo.",
		"vanitylabelstep2calculateyourvanitywallet": "Passo 2 - Calcule sua carteira Vanity",
		"vanitylabelenteryourpart": "Introduza a chave privada gerada no passo 1 acima, e que você já tem guardada:",
		"vanitylabelenteryourpoolpart": "Introduza a chave privada obtida no Vanity Pool:",
		"vanitylabelnote1": "[NOTA: essa caixa de texto pode aceitar uma chave pública ou privada]",
		"vanitylabelnote2": "[NOTA: essa caixa de texto pode aceitar uma chave pública ou privada]",
		"vanitylabelradioadd": "Adicionar",
		"vanitylabelradiomultiply": "Multiplicar",
		"vanitycalc": "Calcular carteira personalizada",
		"vanitylabelbitcoinaddress": "Endereço Bitcoin Vanity:",
		"vanitylabelnotesbitcoinaddress": "Esse é o seu novo endereço, que deveria conter o seu prefixo exigido.",
		"vanitylabelpublickeyhex": "Chave pública Vanity (HEX):",
		"vanitylabelnotespublickeyhex": "Essa é a sua chave pública em formato hexadecimal.",
		"vanitylabelprivatekey": "Chave privada Vanity (WIF):",
		"vanitylabelnotesprivatekey": "Essa é a chave privada para introduzir em sua carteira.",

		// split wallet html
		"splitlabelthreshold": "Limite mínimo de partes necessárias para combinar",
		"splitlabelshares": "Número de partes",
		"splitview": "Gerar",
		"combinelabelentershares": "Insira as partes disponíveis (separadas por espaços)",
		"combineview": "Combinar Partes",
		"combinelabelprivatekey": "Chave Privada Combinada",

		// detail wallet html
		"detaillabelenterprivatekey": "Insira sua chave privada",
		"detailkeyformats": "Formatos de chave: WIF, WIFC, HEX, B64, B6, MINI, BIP38",
		"detailview": "Ver detalhes",
		"detailprint": "Imprimir",
		"detaillabelnote1": "Sua chave privada é um número secreto, único, que somente você tem acesso. Ela pode ser expressa em vários formatos. Abaixo mostramos o endereço e a chave pública que correspondem à sua chave privada, assim como a chave privada nos formatos mais conhecidos (WIF, hex, base64 y mini).",
		"detaillabelnote2": "As versões do Bitcoin acima da v0.6+ armazenam as chaves públicas comprimidas. O cliente também suporta a importação/exportação de chaves privadas usando importprivkey/dumpprivkey. O formato das chaves privadas exportadas depende se o endereço foi gerado em uma carteira antiga ou nova.",
		"detaillabelbitcoinaddress": "Endereço Bitcoin (Legacy P2PKH)",
		"detaillabelbitcoinaddresscomp": "Endereço Bitcoin Comprimido (Legacy P2PKH)",
		"detaillabelP2SH": "Endereço P2SH-P2WPKH (3…)",
		"detaillabelSegwit": "SegWit Nativo P2WPKH (bc1q…)",
		"detaillabelTaproot": "Taproot P2TR (bc1p…)",
		"detaillabelpublickey": "Chave pública (130 caracteres [0-9A-F]):",
		"detaillabelpublickeycomp": "Chave pública (comprimida, 66 caracteres [0-9A-F]):",
		"detaillabelprivwif": "Chave privada para importação (51 caracteres em base58, inicia com um",
		"detaillabelprivwifcomp": "Chave privada para importação (comprimida, 52 caracteres em base58, inicia com",
		"detailcompwifprefix": "'K' ou 'L'",
		"detaillabelprivhex": "Chave privada em formato hexadecimal (64 caracteres [0-9A-F]):",
		"detaillabelprivb64": "Chave privada em base64 (44 caracteres):",
		"detaillabelprivmini": "Chave privada en formato mini (22, 26 ou 30 caracteres, inicia com 'S'):",
		"detaillabelpassphrase": "Senha BIP38",
		"detailbip38decryptbutton": "Descriptografar BIP38",
		"detailbip38encryptbutton": "Criptografar em BIP38",
		"detaillabelq1": "Como eu faço uma carteira usando um dado? O que é o formato B6?",
		"detaila1": "Uma parte importante ao criar um carteira Bitcoin é se assegurar que os números aleatórios usados para criar a carteira sejam realmente aleatórios. A aleatoriedade física é melhor do que a pseudo-aleatoriedade gerada por computador. A maneira mais fácil de gerar aleatoriedade física é com dados. Para criar um chave privada Bitcoin você precisa de apenas um dado de seis lados, o qual você jogará 99 vezes. A cada jogada, anote o valor do dado. Ao anotar os valores, siga as seguintes regras: 1=1, 2=2, 3=3, 4=4, 5=5, 6=0. Ao fazer isso, você está anotando esse grande número aleatório, sua chave privada, no formato base 6 (B6). Você pode então digitar essa chave privada em base 6 contendo 99 caracteres no campo de texto acima e clicar em Ver Detalhes. Você então verá o endereço Bitcoin associado com sua chave privada. Você deve também anotar sua chave privada no formato WIF, já que ele é mais amplamente utilizado.",
		"bulklabelencrypt": "Criptografar em BIP38?",
		"detaillabelencrypt": "Criptografar em BIP38?",
		"bulklabelBIPpassphrase": "Senha:",
		"brainlabelcompressed": "Endereço comprimido?",
		"detailwifprefix": "'5'",
		"detaillabelprivb6": "Chave Privada Formato Base6 (99 caracteres [0-5]):"
	};
})(ninja.translator);
